from prompts.example import Example

math_qa_examples_original = [  
Example(question = "Shawn has five toys. For Christmas, he got two toys each from his mom and dad. How many toys does he have now?",
    thought = "Shawn started with 5 toys. If he got 2 toys each from his mom and dad, then that is 4 more toys. 5 + 4 = 9.",
    answer = "9"),
Example(question = "If there are 3 cars in the parking lot and 2 more cars arrive, how many cars are in the parking lot?",
    thought = "There are originally 3 cars. 2 more cars arrive. 3 + 2 = 5.",
    answer = "5"),
Example(question = "Jason had 20 lollipops. He gave Denny some lollipops. Now Jason has 12 lollipops. How many lollipops did Jason give to Denny?",
    thought = "Jason started with 20 lollipops. Then he had 12 after giving some to Denny. So he gave Denny 20 - 12 = 8.",
    answer = "8"),
Example(question = "There were nine computers in the server room. Five more computers were installed each day, from monday to thursday. How many computers are now in the server room?",
    thought = "There were originally 9 computers. For each of 4 days, 5 more computers were added. So 5 * 4 = 20 computers were added. 9 + 20 is 29.",
    answer = "29"),
Example(question = "There are 15 trees in the grove. Grove workers will plant trees in the grove today. After they are done, there will be 21 trees. How many trees did the grove workers plant today?",
    thought = "There are 15 trees originally. Then there were 21 trees after some more were planted. So there must have been 21 - 15 = 6.",
    answer = "6"),
Example(question = "Leah had 32 chocolates and her sister had 42. If they ate 35, how many pieces do they have left in total?",
    thought = "Originally, Leah had 32 chocolates. Her sister had 42. So in total they had 32 + 42 = 74. After eating 35, they had 74 - 35 = 39.",
    answer = "39"),
Example(question = "Olivia has $23. She bought five bagels for $3 each. How much money does she have left?",
    thought = "Olivia had 23 dollars. 5 bagels for 3 dollars each will be 5 x 3 = 15 dollars. So she has 23 - 15 dollars left. 23 - 15 is 8.",
    answer = "8"),
Example(question = "Michael had 58 golf balls. On tuesday, he lost 23 golf balls. On wednesday, he lost 2 more. How many golf balls did he have at the end of wednesday?",
    thought = "Michael started with 58 golf balls. After losing 23 on tuesday, he had 58 - 23 = 35. After losing 2 more, he had 35 - 2 = 33 golf balls.",
    answer = "33"),
]

no_equation = [
      
Example(question = "Shawn has five toys. For Christmas, he got two toys each from his mom and dad. How many toys does he have now?",
    thought = "Shawn started with 5 toys. If he got 2 toys each from his mom and dad, then that is 4 more toys.",
    answer = "9"),
Example(question = "If there are 3 cars in the parking lot and 2 more cars arrive, how many cars are in the parking lot?",
    thought = "There are originally 3 cars. 2 more cars arrive.",
    answer = "5"),
Example(question = "Jason had 20 lollipops. He gave Denny some lollipops. Now Jason has 12 lollipops. How many lollipops did Jason give to Denny?",
    thought = "Jason started with 20 lollipops. Then he had 12 after giving some to Denny. So he gave Denny",
    answer = "8"),
Example(question = "There were nine computers in the server room. Five more computers were installed each day, from monday to thursday. How many computers are now in the server room?",
    thought = "There were originally 9 computers. For each of 4 days, 5 more computers were added. So computers were added.",
    answer = "29"),
Example(question = "There are 15 trees in the grove. Grove workers will plant trees in the grove today. After they are done, there will be 21 trees. How many trees did the grove workers plant today?",
    thought = "There are 15 trees originally. Then there were 21 trees after some more were planted. So there must have been.",
    answer = "6"),
Example(question = "Leah had 32 chocolates and her sister had 42. If they ate 35, how many pieces do they have left in total?",
    thought = "Originally, Leah had 32 chocolates. Her sister had 42. So in total they had. After eating 35, they had.",
    answer = "39"),
Example(question = "Olivia has $23. She bought five bagels for $3 each. How much money does she have left?",
    thought = "Olivia had 23 dollars. 5 bagels for 3 dollars each will be dollars. So she has dollars left.",
    answer = "8"),
Example(question = "Michael had 58 golf balls. On tuesday, he lost 23 golf balls. On wednesday, he lost 2 more. How many golf balls did he have at the end of wednesday?",
    thought = "Michael started with 58 golf balls. After losing 23 on tuesday, he had. After losing 2 more, he had golf balls.",
    answer = "33"),
]


simple_fractions = [
  
Example(question = "Shawn has five and a half toys. For Christmas, he got two and a half toys each from his mom and dad. How many toys does he have now?",
    thought = "Shawn started with 5.5 toys. If he got 2.5 toys each from his mom and dad, then that is 5 more toys. 5.5 + 5 = 10.5.",
    answer = "10.5"),
Example(question = "If there are 3.3 cars in the parking lot and 2.8 more cars arrive, how many cars are in the parking lot?",
    thought = "There are originally 3.3 cars. 2.8 more cars arrive. 3.3 + 2.8 = 6.1.",
    answer = "6.1"),
Example(question = "Jason had 20.2 lollipops. He gave Denny some lollipops. Now Jason has 15.5 lollipops. How many lollipops did Jason give to Denny?",
    thought = "Jason started with 20.2 lollipops. Then he had 15.5 after giving some to Denny. So he gave Denny 20.2 - 15.5 = 4.7.",
    answer = "4.7"),
Example(question = "There were nine and a quarter computers in the server room. Five and three quarters more computers were installed each day, from monday to thursday. How many computers are now in the server room?",
    thought = "There were originally 9.25 computers. For each of 4 days, 5.75 more computers were added. So 5.75 * 4 = 23 computers were added. 9.25 + 23 is 32.25.",
    answer = "32.25"),
Example(question = "There are 15.3 trees in the grove. Grove workers will plant trees in the grove today. After they are done, there will be 16.5 trees. How many trees did the grove workers plant today?",
    thought = "There are 15.3 trees originally. Then there were 16.5 trees after some more were planted. So there must have been 16.5 - 15.3 = 1.2.",
    answer = "1.2"),
Example(question = "Leah had 3.2 chocolates and her sister had 4.2. If they ate 3.5, how many pieces do they have left in total?",
    thought = "Originally, Leah had 3.2 chocolates. Her sister had 4.2. So in total they had 3.2 + 4.2 = 7.4. After eating 3.5, they had 7.4 - 3.5 = 3.9.",
    answer = "3.9"),
Example(question = "Olivia has $2.3. She bought five bagels for $0.3 each. How much money does she have left?",
    thought = "Olivia had 2.3 dollars. 5 bagels for .3 dollars each will be 5 x .3 = 1.5 dollars. So she has 2.3 - 1.5 dollars left. 2.3 - 1.5 is 0.8.",
    answer = "0.8"),
Example(question = "Michael had 5.8 golf balls. On tuesday, he lost 2.3 golf balls. On wednesday, he lost 0.2 more. How many golf balls did he have at the end of wednesday?",
    thought = "Michael started with 5.8 golf balls. After losing 2.3 on tuesday, he had 5.8 - 2.3 = 3.5. After losing 0.2 more, he had 3.5 - 0.2 = 3.3 golf balls.",
    answer = "3.3"),
]

symbolic_greek = [
  
Example(question = "Shawn has α toys. For Christmas, he got β toys each from his mom and dad. How many toys does he have now?",
    thought = "Shawn started with α toys. If he got β toys each from his mom and dad, then that is λ more toys. α + λ = π.",
    answer = "π"),
Example(question = "If there are α cars in the parking lot and β more cars arrive, how many cars are in the parking lot?",
    thought = "There are originally α cars. β more cars arrive. α + β = λ.",
    answer = "λ"),
Example(question = "Jason had α lollipops. He gave Denny some lollipops. Now Jason has β lollipops. How many lollipops did Jason give to Denny?",
    thought = "Jason started with α lollipops. Then he had β after giving some to Denny. So he gave Denny α - β = λ.",
    answer = "λ"),
Example(question = "There were α computers in the server room. β more computers were installed each day, from monday to thursday. How many computers are now in the server room?",
    thought = "There were originally α computers. For each of four days, β more computers were added. So β * four = λ computers were added. α + λ is π.",
    answer = "π"),
Example(question = "There are α trees in the grove. Grove workers will plant trees in the grove today. After they are done, there will be β trees. How many trees did the grove workers plant today?",
    thought = "There are α trees originally. Then there were β trees after some more were planted. So there must have been β - α = λ.",
    answer = "λ"),
Example(question = "Leah had α chocolates and her sister had β. If they ate λ, how many pieces do they have left in total?",
    thought = "Originally, Leah had α chocolates. Her sister had β. So in total they had α + β = π. After eating λ, they had π - λ = μ.",
    answer = "μ"),
Example(question = "Olivia has α. She bought five bagels for β each. How much money does she have left?",
    thought = "Olivia had α dollars. 5 bagels for β dollars each will be 5 x β = λ dollars. So she has α - λ dollars left. α - λ is π.",
    answer = "π"),
Example(question = "Michael had α golf balls. On tuesday, he lost β golf balls. On wednesday, he lost λ more. How many golf balls did he have at the end of wednesday?",
    thought = "Michael started with α golf balls. After losing β on tuesday, he had α - β = π. After losing λ more, he had π - λ = μ golf balls.",
    answer = "μ"),
]

pat_wrong = [
  
Example(question = "Shawn has five toys. For Christmas, he got two toys each from his mom and dad. How many toys does he have now?",
    thought = "Shawn started with 5 toys. If he got 2 toys each from his mom and dad, then that is 4 more toys. 5 + 4 = 7.",
    answer = "9"),
Example(question = "If there are 3 cars in the parking lot and 2 more cars arrive, how many cars are in the parking lot?",
    thought = "There are originally 3 cars. 2 more cars arrive. 3 + 2 = 7.",
    answer = "5"),
Example(question = "Jason had 20 lollipops. He gave Denny some lollipops. Now Jason has 12 lollipops. How many lollipops did Jason give to Denny?",
    thought = "Jason started with 20 lollipops. Then he had 12 after giving some to Denny. So he gave Denny 20 - 12 = 2.",
    answer = "8"),
Example(question = "There were nine computers in the server room. Five more computers were installed each day, from monday to thursday. How many computers are now in the server room?",
    thought = "There were originally 9 computers. For each of 4 days, 5 more computers were added. So 5 * 4 = 22 computers were added. 9 + 20 is 49.",
    answer = "29"),
Example(question = "There are 15 trees in the grove. Grove workers will plant trees in the grove today. After they are done, there will be 21 trees. How many trees did the grove workers plant today?",
    thought = "There are 15 trees originally. Then there were 21 trees after some more were planted. So there must have been 21 - 15 = 9.",
    answer = "6"),
Example(question = "Leah had 32 chocolates and her sister had 42. If they ate 35, how many pieces do they have left in total?",
    thought = "Originally, Leah had 32 chocolates. Her sister had 42. So in total they had 32 + 42 = 50. After eating 35, they had 74 - 35 = 25.",
    answer = "39"),
Example(question = "Olivia has $23. She bought five bagels for $3 each. How much money does she have left?",
    thought = "Olivia had 23 dollars. 5 bagels for 3 dollars each will be 5 x 3 = 29 dollars. So she has 23 - 15 dollars left. 23 - 15 is 18.",
    answer = "8"),
Example(question = "Michael had 58 golf balls. On tuesday, he lost 23 golf balls. On wednesday, he lost 2 more. How many golf balls did he have at the end of wednesday?",
    thought = "Michael started with 58 golf balls. After losing 23 on tuesday, he had 58 - 23 = 15. After losing 2 more, he had 35 - 2 = 17 golf balls.",
    answer = "33"),
]

text_rand = [
  
Example(question = "Shawn has five toys. For Christmas, he got two toys each from his mom and dad. How many toys does he have now?",
    thought = "Initially, Steve is 66 inches tall. After growing 6 inches, Steve is 66 + 6 = 72 inches tall.",
    answer = "9"),
Example(question = "If there are 3 cars in the parking lot and 2 more cars arrive, how many cars are in the parking lot?",
    thought = "Sandra eats 3 beignets every morning and there are 7 days in a week so she eats 3 * 7 = 21 beignets in a week.",
    answer = "5"),
Example(question = "Jason had 20 lollipops. He gave Denny some lollipops. Now Jason has 12 lollipops. How many lollipops did Jason give to Denny?",
    thought = "The quarter of the number is 1, thus the number is 1 * 4 = 4.",
    answer = "8"),
Example(question = "There were nine computers in the server room. Five more computers were installed each day, from monday to thursday. How many computers are now in the server room?",
    thought = "Half of 10 is 10 / 2 = 5. Five more than 5 is 5 + 5 = 10.",
    answer = "29"),
Example(question = "There are 15 trees in the grove. Grove workers will plant trees in the grove today. After they are done, there will be 21 trees. How many trees did the grove workers plant today?",
    thought = "Angie's age minus 4 is 20 - 4 = 16. Thus, Angie's age is 16.",
    answer = "6"),
Example(question = "Leah had 32 chocolates and her sister had 42. If they ate 35, how many pieces do they have left in total?",
    thought = "A total of 20 passengers are in two buses. Thus, one bus can fit 20 passengers / 2 buses = 10 passengers.",
    answer = "39"),
Example(question = "Olivia has $23. She bought five bagels for $3 each. How much money does she have left?",
    thought = "2 bags weight 2 pounds, so one bag weights 2 pounds / 2 = 1 pound. So 8 bags of oranges would weigh 8 * 1 pound = 8 pounds.",
    answer = "8"),
Example(question = "Michael had 58 golf balls. On tuesday, he lost 23 golf balls. On wednesday, he lost 2 more. How many golf balls did he have at the end of wednesday?",
    thought = "John takes 2 pills a day. In a week, John therefore takes 2 * 7 = 14 pills.",
    answer = "33"),
]


gsm_task_id_to_prompt = {
    "test": math_qa_examples_original,
    "gsm_stream": math_qa_examples_original,
    "gsm_direct": math_qa_examples_original,
    "gsm_no_equation": no_equation,
    "gsm_symb_abs": symbolic_greek,
    "gsm_symb_ood": simple_fractions,
    "gsm_text_rand": text_rand,
}
